name: Load SSH Key
description: Loads an SSH key from an AWS secret
author: https://github.com/melodics-thomas
requirements: ["aws"]
configuration:
  type: "object"
  properties:
    secret:
      type: string
  required: ["secret"]
  additionalProperties: false
