#!/bin/bash

set -eo pipefail

SSH_KEY_SECRET_NAME="${BUILDKITE_PLUGIN_LOAD_SSH_KEY_SECRET}"

echo "~~~ :key: Loading SSH key from \"${SSH_KEY_SECRET_NAME}\"..."

if [[ -z "${SSH_KEY_SECRET_NAME}" ]]; then
  echo "Error: No secret name was set!" >&2;
  exit 1;
fi

SSH_KEY=$(
aws secretsmanager get-secret-value \
  --secret-id "$SSH_KEY_SECRET_NAME" \
  --query SecretString \
  --output text
)

if [[ -z "${SSH_KEY}" ]] ; then
  echo "SSH key could not be loaded" >&2;
  exit 1;
else
  echo "${#SSH_KEY} character SSH key loaded"
fi

if [[ -z "${SSH_AGENT_PID:-}" ]] ; then
  echo "Starting an ephemeral ssh-agent..."
  eval "$(ssh-agent -s)"
fi

echo "Loading SSH key into ssh-agent (pid ${SSH_AGENT_PID:-})..."
echo "$SSH_KEY" | env SSH_ASKPASS="/bin/false" ssh-add -
echo "SSH key loaded!"
